### PR TITLE
generate dots svg for use in readme

### LINKED ISSUE #2: Generate SVG displaying palette for docs
I was thinking yesterday it might be nice to show the palette in the readme. I see you've done that now with a PNG. Github supports SVG files in markdown. 

Perhaps we could generate an SVG for display in the readme? Happy to give it a go

### PR DESCRIPTION
**Pull request by WickyNilliams**
fixes #2

### CODE REVIEW

**Comment by WickyNilliams** [comment]
One immediately obvious difference here is you only have 12 colours in your dots.png, but there are 16 colours in the theme. Wondering if this was intentional, or if it just fell out of sync?

**Comment by drcmda** [comment]
i was just too lazy to copy them all, 16 is good :-)

**Comment by WickyNilliams** [comment]
Haha fair enough, easy to do

**Comment by drcmda** [comment]
turns out visual studio doesnt allow svgs :-S we still need to convert it to png somehow

**Comment by drcmda** [comment]
fixed it, thanks! :-)

**Comment by WickyNilliams** [comment]
Hadn't even considered vscode won't allow it for extensions since it works fine in the markdown preview within vscode. Glad it was a simple fix!

**Pull request merged**
