### PR TITLE
generate higher resolution dots image

### PR DESCRIPTION
**Pull request by WickyNilliams**
Part of my decision to use SVG originally was to ensure a sharp image, but we lost that when converting back to png. This should fix.

I chose 400ppi after looking at pixel densities of various apple devices. This can probably be tweaked to find optimal intersection of resolution and file size. 

In any case, it's crisp now!

I added `width` back to the `` tag in readme, as the height/width on the SVG is lost during conversion.

### CODE REVIEW

**Comment by drcmda** [comment]
conflicts for some reason, could you amend?

**Comment by WickyNilliams** [comment]
Sure, yeah no problems.

I wonder if dots.png should be gitignored since it is auto-generated? Just means you would need to run a build before packaging/publishing the theme to the vscode marketplace

**Comment by drcmda** [comment]
i think the marketplace pulls the image from git

**Comment by WickyNilliams** [comment]
Ah ok, I thought it might work like npm where you can publish things that aren't part of the repo, eg. ignored files. Nevermind then!

**Comment by drcmda** [comment]
i copied these changes over into master, thanks again! :-)

**Comment by WickyNilliams** [comment]
OK no worries. Didn't have time to do it today, cheers for getting it in

**Pull request closed without merging**
