### PR TITLE
fix transparent list.inactiveSelectionBackground

### PR DESCRIPTION
**Pull request by brokenthorn**
This PR fixes the transparent inactive selection background color for lists, include the file explorer.

### CODE REVIEW

**Comment by brokenthorn** [comment]
@drcmda Please review.

**Comment by drcmda** [comment]
it's a bit odd, there are no light themes any longer. updating the json isn't correct bc these will be overwritten by a script. the right place is theme.js, but again, light fell out long ago.

**Comment by brokenthorn** [comment]
@drcmda sorry. I have no idea how this works. The changes worked during dev so I assumed that was it.

OK. I need to read more on how VSCode themes work. I will fix as soon as possible.

**Comment by drcmda** [comment]
the thing is, i removed light themes because it didn't really fit in. i started with a dark theme, then people suggested a light variant. i made it but it had little to do with the distinct pmndrs look, it was basically just some light theme. eventually i deleted the files and decide to only ship the dark variant.

**Comment by brokenthorn** [comment]
Sorry, no time...

**Pull request closed without merging**
